In [1]:
import numpy as np

In [32]:
a = np.array([1,2,3])
b = np.array([[1,2,3],[4,5,6]])

In [ ]:
#slicing methods for 1D array
print(a[1:2])
print(a[:2])
print(a[1:])

[2]
[1 2]
[2 3]


In [17]:
#slicing method for 2D array
print(b[1, 1:2])
print(b[0:2,2])
print(b[:,2])
print(b[1,:])
print(b[1,2])
print(b[0:2,0:2])
print(b[:,:])

[5]
[3 6]
[3 6]
[4 5 6]
6
[[1 2]
 [4 5]]
[[1 2 3]
 [4 5 6]]


In [ ]:
#boolean indexing : if condition is true then print element 
a[a>1]

array([2, 3])

In [ ]:
#slicing by elements it will gicve elements of exact index
a[[0,2]]

array([1, 3])

In [20]:
#in array you cannot store multiple datatype in one array if you want to do that you need to define it as a object or else it will automatically consider all as a string 
arr = np.array( ['arpita',2 ,4, 6.7, 10])

In [ ]:
arr  # all considered as string because int can be written into string 

array(['arpita', '2', '4', '6.7', '10'], dtype='<U32')

In [25]:
arr1 = np.array(['arpita',2 ,4, 6.7, 10], dtype=object)

In [ ]:
arr1 # all remain as it is becuse of object typr 

array(['arpita', 2, 4, 6.7, 10], dtype=object)

In [37]:
ar1 = np.array([1,2,3])
ar2 = np.array([4,5,6])

In [ ]:
#basic arithmatic operation
print("addition:",ar1+ar2)
print("substraction:",  ar1-ar2)
print("multiplication:", ar1*ar2)
print("division:", ar2/ar1)
print("power:",ar1**2)


addition: [5 7 9]
substraction: [-3 -3 -3]
multiplication: [ 4 10 18]
division: [4.  2.5 2. ]
power: [1 4 9]


In [42]:
# functions 
print(np.sqrt(ar1))
print(np.exp(ar1))
print(np.log(ar1))


[1.         1.41421356 1.73205081]
[ 2.71828183  7.3890561  20.08553692]
[0.         0.69314718 1.09861229]


In [43]:
print(np.sum(ar1))
print(np.min(ar1))
print(np.max(ar1))
print(np.mean(ar1))
print(np.std(ar1))

6
1
3
2.0
0.816496580927726


In [ ]:
#broadcasting
a = np.array([1,2,3])
b = 3
a+b # b will be added to each element of a 

array([4, 5, 6])

In [45]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([2,4,6])
a+b # b will be added to each row of a 

array([[ 3,  6,  9],
       [ 6,  9, 12]])

In [46]:
a = np.array([[1],[2],[3]])
b = np.array([10,20,30])
a+b

array([[11, 21, 31],
       [12, 22, 32],
       [13, 23, 33]])

In [ ]:
#make 3x3 array from random 1to 10 and get mean from each coloum.
a = np.arange(1,10).reshape(3,3)
print(a)
a.mean(axis=0)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([4., 5., 6.])

In [ ]:
#matrix multiplication (dot product)
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
np.dot(a,b)
a@b

array([[19, 22],
       [43, 50]])

In [100]:
#iterating array with different datatype

arr = np.array([1,2,3,4,5])
for i in np.nditer(arr):
    print(i)

for i in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
    print(i)

for i in np.nditer(arr[::2]):
    print(i)

arr1 = np.array([[1,2,3],[4,5,6]])

for i in np.nditer(arr1[:,::2]):
    print(i)

1
2
3
4
5
np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')
np.bytes_(b'4')
np.bytes_(b'5')
1
3
5
1
3
4
6


In [102]:
#ndenumerate function which give iterate with index
for index,i in np.ndenumerate(arr):
    print(index, i)

for index, i in np.ndenumerate(arr1):
    print(index, i)

(0,) 1
(1,) 2
(2,) 3
(3,) 4
(4,) 5
(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6


In [120]:
#join array 

a1 = np.array([[1,2],[3,4]])
a2 = np.array([[5,6],[7,8]])

a3 = np.concatenate((a1, a2))
print(a3)

a4 = np.stack((a1,a2),axis=1) #bydefault it will take 0 as axis 
print(a4)

a5 = np.hstack((a1,a2)) #stack along rows
print(a5)

a6 = np.vstack((a1,a2)) #stack over coloumn 
print(a6)

a7 = np.dstack((a1,a2)) #stack over depth
print(a7)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]
[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]
