### Task 2: Numpy

1. Make 1D array of numpy with numbers 10 to 20 (inclusive)
2. Make the above array to new array of size (5,2)
3. Make new array of shape (5,5) with all elements randomly intialized
4. Make a new array of all 1's of size 10

In [21]:
import numpy as np
from numpy import random

In [22]:
arr = np.arange(10,20)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [23]:
arr.shape

(10,)

In [24]:
arr.resize((5,2))
arr

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [25]:
arr = random.random(size=(5,5))
arr

array([[0.59699989, 0.52545928, 0.52116503, 0.97908648, 0.97733615],
       [0.13970871, 0.32000482, 0.92622168, 0.55177451, 0.89616042],
       [0.4623205 , 0.93643556, 0.81914149, 0.97512082, 0.06541888],
       [0.68768797, 0.39180157, 0.35052361, 0.73774875, 0.36972207],
       [0.04656165, 0.57714393, 0.82905052, 0.36458607, 0.30215017]])

In [26]:
arr = random.choice([1], size=(10))
arr

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### Task 1: Pandas
1. Import the dataframe
2. Find data types of the columns using inbuilt function
3. List all the unique values in the “Department” column and clean the mistake
4. Drop missing data/NA data from the column 'Score'
5. Rename columns “Date Joined” → “JoinedDate” and “Score” → “PerformanceScore”
6. Drop duplicate rows based on the “ID” column, keeping only the first occurrence
7. 'Departments' may have extra spaces or inconsistent casing, strip whitespace and capitalize each department name
8. Save the new dataframe to csv

In [27]:
import pandas as pd

In [28]:
df = pd.read_csv("messy_data.csv")
df

ID     Name    Age     Date Joined  Score Department
0  1.0    Alice   TRUE      2021-01-15   88.5      Sales
1  2.0     Bob   FALSE      15/02/2021   92.0      sales
2  2.0  Charlie     40      2021-03-05    NaN         HR
3  NaN     Dave     35  April 10, 2021   85.0        HR 
4  5.0      NaN    NaN      2021.05.01   90.0    finance
5  6.0      Eve     28      2021-06-01    NaN    Finance

In [29]:
print(df["ID"].astype)
print(df["Name"].astype)
print(df["Age"].astype)
print(df["Date Joined"].astype)
print(df["Score"].astype)
print(df["Department"].astype)

<bound method NDFrame.astype of 0    1.0
1    2.0
2    2.0
3    NaN
4    5.0
5    6.0
Name: ID, dtype: float64>
<bound method NDFrame.astype of 0      Alice
1       Bob 
2    Charlie
3       Dave
4        NaN
5        Eve
Name: Name, dtype: object>
<bound method NDFrame.astype of 0     TRUE
1    FALSE
2       40
3       35
4      NaN
5       28
Name: Age, dtype: object>
<bound method NDFrame.astype of 0        2021-01-15
1        15/02/2021
2        2021-03-05
3    April 10, 2021
4        2021.05.01
5        2021-06-01
Name: Date Joined, dtype: object>
<bound method NDFrame.astype of 0    88.5
1    92.0
2     NaN
3    85.0
4    90.0
5     NaN
Name: Score, dtype: float64>
<bound method NDFrame.astype of 0      Sales
1      sales
2         HR
3        HR 
4    finance
5    Finance
Name: Department, dtype: object>


In [30]:
df["Department"].unique()

array(['Sales', 'sales', 'HR', 'HR ', 'finance', 'Finance'], dtype=object)

In [31]:
df["Department"] = df["Department"].str.strip().str.capitalize()
df["Department"].unique()

array(['Sales', 'Hr', 'Finance'], dtype=object)

In [32]:
df.dropna(subset=['Score'], inplace=True)
df

ID    Name    Age     Date Joined  Score Department
0  1.0   Alice   TRUE      2021-01-15   88.5      Sales
1  2.0    Bob   FALSE      15/02/2021   92.0      Sales
3  NaN    Dave     35  April 10, 2021   85.0         Hr
4  5.0     NaN    NaN      2021.05.01   90.0    Finance

In [33]:
df.rename(columns={"Date Joined": "JoinedDate", "Score": "PerformanceScore"}, inplace=True)
df

ID    Name    Age      JoinedDate  PerformanceScore Department
0  1.0   Alice   TRUE      2021-01-15              88.5      Sales
1  2.0    Bob   FALSE      15/02/2021              92.0      Sales
3  NaN    Dave     35  April 10, 2021              85.0         Hr
4  5.0     NaN    NaN      2021.05.01              90.0    Finance

In [34]:
#6. Drop duplicate rows based on the “ID” column, keeping only the first occurrence
df.drop_duplicates(subset=['ID'], keep='first', inplace=True)
df

ID    Name    Age      JoinedDate  PerformanceScore Department
0  1.0   Alice   TRUE      2021-01-15              88.5      Sales
1  2.0    Bob   FALSE      15/02/2021              92.0      Sales
3  NaN    Dave     35  April 10, 2021              85.0         Hr
4  5.0     NaN    NaN      2021.05.01              90.0    Finance

In [35]:
df.drop_duplicates("ID")

ID    Name    Age      JoinedDate  PerformanceScore Department
0  1.0   Alice   TRUE      2021-01-15              88.5      Sales
1  2.0    Bob   FALSE      15/02/2021              92.0      Sales
3  NaN    Dave     35  April 10, 2021              85.0         Hr
4  5.0     NaN    NaN      2021.05.01              90.0    Finance

In [36]:
df = pd.DataFrame(df)
df

ID    Name    Age      JoinedDate  PerformanceScore Department
0  1.0   Alice   TRUE      2021-01-15              88.5      Sales
1  2.0    Bob   FALSE      15/02/2021              92.0      Sales
3  NaN    Dave     35  April 10, 2021              85.0         Hr
4  5.0     NaN    NaN      2021.05.01              90.0    Finance

In [37]:
def fun1(word):
    word = word.strip()
    a = word.upper()
    return a

df["Department"] = df["Department"].apply(fun1)
df["Department"].unique()

array(['SALES', 'HR', 'FINANCE'], dtype=object)

In [ ]:
df.to_csv("new_data.csv") # saved 