In [2]:
import numpy as np

In [3]:
a = [3,4,6,2,9]

In [4]:
arr = np.array(a)
(arr)

array([3, 4, 6, 2, 9])

In [54]:
arr1= np.array([2,3,4,5], np.int8) #1d array 
print(arr1) #.int_ method will allocate memory based on byte if you write int8, int16 or int32 or int64 it will aloocate based on that 
ar1 = np.array([1,2,3], ndmin=3) #set the dimention of the given array
print(ar1.ndim)

[2 3 4 5]
3


In [6]:
arr2 = np.array([[1,3,6],[8,1,3]])  #2d array
arr2
arr2[1,2]

np.int64(3)

In [7]:
arr.shape#it will define shape of the array based on elements and it's type
arr1.shape
arr2.shape
arr.dtype  #it will define memory allocation of that variable
arr1.dtype
arr2.dtype

dtype('int64')

In [8]:
#types to define numpy array 
#1. python datatypes
list  = [3,5,7]
l = np.array(list)
l #when in last line then only work
print(l)
#2. built-in methods 
z = np.zeros((3,5)) #zeros will return float values of 0 and dimention as mention 
print(z)
a = np.arange(10) # it will give one dimention array upto the range, last element is not considered
print(a)
#linespace
lspace = np.linspace(1,3,4) #from 1 to 3 divide elemets into 4 equal parts 
print(lspace)
#empty 
e = np.empty((1,3)) #it will take random number and print array
print(e)
e2 = np.empty_like(a) 
print(e2)
#identity
i = np.identity(5) # it will give identity array of parameter given 
print(i)
#RESHAPE
s = np.arange(99)
r = s.reshape(3,33)
print(s)
print(r)
print(r.ravel())

[3 5 7]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[0 1 2 3 4 5 6 7 8 9]
[1.         1.66666667 2.33333333 3.        ]
[[0. 0. 0.]]
[         4294967296                   0          4294967298
 4851316189630038017                 924 7308602722113028507
                1056 2893965658582679963                 748
 8386098755551625627]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98]
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24 25 26 27 28 29 30 31 32]
 [33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56
  57 58 59 60 61 62 63 64 65]
 [66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81

In [9]:
a = [[2,5,3,6],[1,4,2,3]]
b = np.array(a)
print(b.sum(axis=0))
print(b.sum(axis=1))

[3 9 5 9]
[16 10]


In [10]:
b.T

array([[2, 1],
       [5, 4],
       [3, 2],
       [6, 3]])

In [11]:
b.flat

In [12]:
for i in b.flat:
    print(i)

2
5
3
6
1
4
2
3


In [53]:
b.ndim  #check number of dimention

2

In [14]:
b.size

8

In [15]:
b.nbytes

64

In [21]:
b = np.array([2,5,3,6])
print(b.argsort())

[0 2 1 3]


In [17]:
b.argsort()

array([[0, 2, 1, 3],
       [0, 2, 3, 1]])

In [18]:
b.argsort(axis=0)

array([[1, 1, 1, 1],
       [0, 0, 0, 0]])

In [19]:
b.argsort(axis=1)

array([[0, 2, 1, 3],
       [0, 2, 3, 1]])

In [22]:
b = np.array([[50, 20, 30],
              [40, 10, 20],
              [60, 30, 10]])

In [24]:
b.argsort(axis=0)

array([[1, 1, 2],
       [0, 0, 1],
       [2, 2, 0]])

In [25]:
b.argsort(axis=1)

array([[1, 2, 0],
       [1, 2, 0],
       [2, 1, 0]])

In [27]:
a = np.array([[1,3,2],[2,4,3]])
b = np.array([[3,5,4],[5,2,1]])


In [30]:
print(a)
print(b)
print(a+b)
print(a*b)

[[1 3 2]
 [2 4 3]]
[[3 5 4]
 [5 2 1]]
[[4 8 6]
 [7 6 4]]
[[ 3 15  8]
 [10  8  3]]


In [33]:
np.sqrt([[16, 81],[9, 4]])

array([[4., 9.],
       [3., 2.]])

In [44]:
arr = np.array([[1,4,2],[5,3,7]])
print(np.where(arr>5)) # return the postion of the value if condition is true #return as tuple
np.where(arr>5,"true","false") # (condition, x,y) if condition is true then return x else y #return array 

(array([1]), array([2]))


array([['false', 'false', 'false'],
       ['false', 'false', 'true']], dtype='<U5')

In [ ]:
ar = np.array([[1,2,0],[2,0,1]])
np.count_nonzero(ar) #return total non zero values into array 

np.int64(4)

In [ ]:
np.nonzero(ar) #return postion of non zero values

(array([0, 0, 1, 1]), array([0, 1, 0, 2]))

In [50]:
ar[1,2] = 0
np.nonzero(ar)

(array([0, 0, 1]), array([0, 1, 0]))

In [52]:
a = np.array(32)
print(a)

32
