### Task 2: Numpy

1. Make 1D array of numpy with numbers 10 to 20 (inclusive)
2. Make the above array to new array of size (5,2)
3. Make new array of shape (5,5) with all elements randomly intialized
4. Make a new array of all 1's of size 10

In [1]:
import numpy as np
from numpy import random

In [2]:
arr = np.arange(10,20)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [3]:
arr.shape

(10,)

In [4]:
arr.resize((5,2))
arr

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [5]:
arr = random.random(size=(5,5))
arr

array([[0.56815913, 0.31160013, 0.16542124, 0.10239099, 0.01597863],
       [0.0978386 , 0.77852886, 0.04831267, 0.24092147, 0.64271634],
       [0.10451469, 0.96559517, 0.83050761, 0.98776528, 0.93598172],
       [0.98525758, 0.32615152, 0.80962437, 0.10298646, 0.74590524],
       [0.5414978 , 0.89220564, 0.63951305, 0.64711827, 0.15707995]])

In [6]:
arr = random.choice([1], size=(10))
arr

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### Task 1: Pandas
1. Import the dataframe
2. Find data types of the columns using inbuilt function
3. List all the unique values in the “Department” column and clean the mistake
4. Drop missing data/NA data from the column 'Score'
5. Rename columns “Date Joined” → “JoinedDate” and “Score” → “PerformanceScore”
6. Drop duplicate rows based on the “ID” column, keeping only the first occurrence
7. 'Departments' may have extra spaces or inconsistent casing, strip whitespace and capitalize each department name
8. Save the new dataframe to csv

In [7]:
import pandas as pd

In [8]:
df = pd.read_csv("messy_data.csv")
df

ID     Name    Age     Date Joined  Score Department
0  1.0    Alice   TRUE      2021-01-15   88.5      Sales
1  2.0     Bob   FALSE      15/02/2021   92.0      sales
2  2.0  Charlie     40      2021-03-05    NaN         HR
3  NaN     Dave     35  April 10, 2021   85.0        HR 
4  5.0      NaN    NaN      2021.05.01   90.0    finance
5  6.0      Eve     28      2021-06-01    NaN    Finance

In [9]:
print(df["ID"].astype)
print(df["Name"].astype)
print(df["Age"].astype)
print(df["Date Joined"].astype)
print(df["Score"].astype)
print(df["Department"].astype)

<bound method NDFrame.astype of 0    1.0
1    2.0
2    2.0
3    NaN
4    5.0
5    6.0
Name: ID, dtype: float64>
<bound method NDFrame.astype of 0      Alice
1       Bob 
2    Charlie
3       Dave
4        NaN
5        Eve
Name: Name, dtype: object>
<bound method NDFrame.astype of 0     TRUE
1    FALSE
2       40
3       35
4      NaN
5       28
Name: Age, dtype: object>
<bound method NDFrame.astype of 0        2021-01-15
1        15/02/2021
2        2021-03-05
3    April 10, 2021
4        2021.05.01
5        2021-06-01
Name: Date Joined, dtype: object>
<bound method NDFrame.astype of 0    88.5
1    92.0
2     NaN
3    85.0
4    90.0
5     NaN
Name: Score, dtype: float64>
<bound method NDFrame.astype of 0      Sales
1      sales
2         HR
3        HR 
4    finance
5    Finance
Name: Department, dtype: object>


In [10]:
df["Department"].unique()

array(['Sales', 'sales', 'HR', 'HR ', 'finance', 'Finance'], dtype=object)

In [ ]:
df.isna()

ID   Name    Age  Date Joined  Score  Department
0  False  False  False        False  False       False
1  False  False  False        False  False       False
2  False  False  False        False   True       False
3   True  False  False        False  False       False
4  False   True   True        False  False       False
5  False  False  False        False   True       False

In [18]:
df.drop_duplicates("ID")

ID    Name    Age     Date Joined  Score Department
0  1.0   Alice   TRUE      2021-01-15   88.5      Sales
1  2.0    Bob   FALSE      15/02/2021   92.0      sales
3  NaN    Dave     35  April 10, 2021   85.0        HR 
4  5.0     NaN    NaN      2021.05.01   90.0    finance
5  6.0     Eve     28      2021-06-01    NaN    Finance

In [11]:
df = pd.DataFrame(df)
df

ID     Name    Age     Date Joined  Score Department
0  1.0    Alice   TRUE      2021-01-15   88.5      Sales
1  2.0     Bob   FALSE      15/02/2021   92.0      sales
2  2.0  Charlie     40      2021-03-05    NaN         HR
3  NaN     Dave     35  April 10, 2021   85.0        HR 
4  5.0      NaN    NaN      2021.05.01   90.0    finance
5  6.0      Eve     28      2021-06-01    NaN    Finance

In [15]:
def fun1(word):
    word = word.strip()
    a = word.upper()

df["Department"].apply(fun1)
df

ID     Name    Age     Date Joined  Score Department
0  1.0    Alice   TRUE      2021-01-15   88.5      Sales
1  2.0     Bob   FALSE      15/02/2021   92.0      sales
2  2.0  Charlie     40      2021-03-05    NaN         HR
3  NaN     Dave     35  April 10, 2021   85.0        HR 
4  5.0      NaN    NaN      2021.05.01   90.0    finance
5  6.0      Eve     28      2021-06-01    NaN    Finance

In [ ]:
df.to_csv("new_data.csv")