In [1]:
import numpy as np

In [15]:
x= np.array([1,2,3])
y = np.array([4,5,6])

z=np.add(x,y) #universal function for adding elements 
print("addition:",z)

a = np.subtract(x,y)
print("substraction:",a)

b = np.multiply(x,y)
print("multiply:",b)

c = np.divide(x,y)
print("divide:",c)

d = np.power(x,y)
print("power:",d)

e = np.mod(x,y)
print("mod:",e)
f = np.remainder(x,y)
print("reminder:",f)

g = np.divmod(x,y)
print(g)

h =np.absolute(x,y)
print(h)

addition: [5 7 9]
substraction: [-3 -3 -3]
multiply: [ 4 10 18]
divide: [0.25 0.4  0.5 ]
power: [  1  32 729]
mod: [1 2 3]
reminder: [1 2 3]
(array([0, 0, 0]), array([1, 2, 3]))
[1 2 3]


In [ ]:
#create your own ufunc using frompyfunc() method 
x = [1,2,3]
y = [4,5,6]

def fun1(x,y):
    return x+y

fun1 = np.frompyfunc(fun1, 2,1)
print(fun1(x,y))

[5 7 9]


In [ ]:
#check if func is ufnc or not

print(type(np.add))
# print(type(np.fun1))  IT WILL GIVE ERROR BECUSE IT IS NOT UFUNC

<class 'numpy.ufunc'>


In [ ]:
#rounding decimals
#1.truncation  : only keep int valus remove numbers after .
a = np.trunc([-1.344, -48.87709])
print(a)

#2. fix : only keep int number
b = np.fix([-1.344, -48.87709])
print(b)

#3. rounding : roundoff value upto given digits
c = np.round(-1.36666666, 2)
print(c)

#4. floor : round off value to nearest lower digit
d = np.floor([-1.344, -48.87709])
print(d)

#5.ceil : roundoff value to nearest higher value
e = np.ceil([-1.344, -48.87709])
print(e)

[ -1. -48.]
[ -1. -48.]
-1.34
[ -2. -49.]
[ -1. -48.]


In [22]:
#logs 
 
a = np.array([1,2,3,4,5])
print(a)
print(np.log2(a)) #log at base2
print(np.log10(a)) # log at base10
print(np.log(a)) #matural log base e

#log at any base
from math import log
nplog = np.frompyfunc(log,2,1)
print(nplog(100,15))

[1 2 3 4 5]
[0.         1.         1.5849625  2.         2.32192809]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
1.7005483074552052


In [ ]:
#summations
x = np.array([1,2,3])
y = np.array([4,5,6])

a = np.add(x,y)
print(a)

b = np.sum([x,y])
print(b)

c = np.sum([x,y], axis=1)
print(c)

d = np.cumsum(x)
print(d)

[5 7 9]
21
[ 6 15]
[1 3 6]


In [ ]:
#products
e = np.prod(x)
print(e)

f = np.prod([x,y])
print(f)

g = np.prod([x,y], axis=1)
print(g)

h = np.cumprod(y)
print(h)

6
720
[  6 120]
[  4  20 120]


In [38]:
#difference
i = np.diff(x)
print(i)

j = np.diff([30, 16, 23, 17], n=2)
print(j)

[1 1]
[ 21 -13]


In [45]:
#lcm :lowest commmon multiple
n1 = 4
n2 = 6

a = np.lcm(n1,n2)
print(a)

c= np.array([3, 6, 9])
b = np.lcm.reduce(c)
print(b)

12
18


In [46]:
#gcd :gratest common divisor

d = np.gcd(n1, n2)
print(d)

e = np.gcd.reduce(c)
print(e)

2
3


In [ ]:
#numpy trigonometric function 

a = np.sin(np.pi/2)
print(a)

b = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])

c = np.sin(c)
print(c)

#convert degree into radient 
d = np.array([90,180,270])
e = np.deg2rad(d)
print(e)

#radient to degree 
f = np.rad2deg(b)
print(f)

#finding angle
g = np.arcsin(1.0)
print(g)

h = np.arcsin([1,-1,0])
print(h)

#hypotenues :pythagorus theorm of triangle
i = 3
j = 4

k = np.hypot(i,j)
print(k)

1.0
[ 0.13838047 -0.25960268  0.35468521]
[1.57079633 3.14159265 4.71238898]
[90. 60. 45. 36.]
1.5707963267948966
[ 1.57079633 -1.57079633  0.        ]
5.0


In [ ]:
#hyperbolic function
l = np.sinh(np.pi/2)
print(l)

m = np.cosh(np.pi/2)
print(m)
 
#finding angles
n = np.arcsinh(1.0)
print(n)

p = np.array([0.1, 0.5])
o = np.arctanh(p)
print(o)

2.3012989023072947
2.5091784786580567
0.881373587019543
[0.10033535 0.54930614]


In [ ]:
# sets in numpy 
a = np.array([1,2,5,7,3,2,7,1,2,5,2,7])

b = np.unique(a)
print(b)

#finding union 
c = np.array([1,3,5,2])
d = np.array([3,5,7,4])

e = np.union1d(c, d)
print(e)

#finding intersection 
f = np.intersect1d(c,d)
print(f)

#difference 
g = np.setdiff1d(c,d)
print(g)

#symmetric difference
h = np.setxor1d(c, d)
print(h) 


[1 2 3 5 7]
[1 2 3 4 5 7]
[3 5]
[1 2]
[1 2 4 7]
